version: "3.9"

services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run page-objects-chrome
    volumes:
      - ./playwright-report/:/app/playwright-report/
      - ./test-results/:/app/test-results/
